In [5]:
import numpy as np 
#q1
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
arr = [1, 2, 3, 4]
n = len(arr)
arr2 = [0] * n
for i in range(n):
    arr2[i] = arr[i] + 2
print(arr2)

[3, 4, 5, 6]


In [15]:
arr3=[0]*n
for i in range(0,n):
    arr3[i]=arr[i]*3
print(arr3)

[3, 6, 9, 12]


In [16]:
arr4=[0]*n
for i in range(0,n):
    arr4[i]=arr[i]/2
print(arr4)

[0.5, 1.0, 1.5, 2.0]


In [20]:
#q2
arr=np.array([1,2,3,6,4,5])
revarr=np.flip(arr)
revarr

array([5, 4, 6, 3, 2, 1])

In [23]:
arr=np.array([1,2,3,4,5,1,2,1,1,1])
freq = {}
for x in arr:
    freq[x] = freq.get(x, 0) + 1
maxfreq = max(freq.values())
for x in freq:
    if freq[x] == maxfreq:
        indices = [i for i in range(len(arr)) if arr[i] == x]
        print("Value:", x)
        print("Frequency:", maxfreq)
        print("Indices:", indices)


Value: 1
Frequency: 5
Indices: [0, 5, 7, 8, 9]


In [27]:
arr=np.array([1,1,1,2,3,4,2,4,3,3])
freq={}
for x in arr:
    freq[x]=freq.get(x,0)+1
maxfreq=max(freq.values())
for x in freq:
    if freq[x]==maxfreq:
       indices=[i for i in range(len(arr)) if arr[i]==x]
       print("value ",x)
       print("frequency ",maxfreq)
       print("indices ",indices)

value  1
frequency  3
indices  [0, 1, 2]
value  3
frequency  3
indices  [4, 8, 9]


In [34]:
#q3
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


In [46]:
#q4
Vanshika=np.linspace(10,100,25)#generates an array of evenly spaced numbers over specified interval
print(Vanshika)
#dimensions
print(Vanshika.ndim)
#shape
print(Vanshika.shape)#for 2d it is row,col; for 3d it is depth,row,col
#total number of elements
print(Vanshika.size)
#data type of each element
print(Vanshika.dtype)
#total number of bytes consumed by the array
print(Vanshika.nbytes)
#reshape 
reshapedarr=Vanshika.reshape(Vanshika.size,1)
print(reshapedarr)
#reshape using .T attribute
Treshape=Vanshika.reshape(-1,1)#-1 is used to figure out the array's dimension by itself
arrreshape=Treshape.T
print(arrreshape)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


In [49]:
#q5
ucs420Vanshika=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
#mean
print(np.mean(ucs420Vanshika))
print(np.median(ucs420Vanshika))
print(np.max(ucs420Vanshika))
print(np.min(ucs420Vanshika))
print(np.unique(ucs420Vanshika))

reshapeducs420Vanshika=np.reshape(ucs420Vanshika,(4,3))
print(reshapeducs420Vanshika)

resizeducs420Vanshika = np.resize(ucs420Vanshika, (2, 3))
print(resizeducs420Vanshika)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
